### PR TITLE
Bump to v1.0.4

### PR DESCRIPTION
**Pull request by mwengren**
@ocefpaf Am I missing anything to build a new release of sensorml2iso in conda-forge? 

Upstream release: https://github.com/ioos/sensorml2iso/releases/tag/v1.0.4

### CODE REVIEW

**Comment by ocefpaf** [comment]
You would need to update the checksum and re-render the feedstock. But we are lazy on `conda-forge` and we let the bot do that for us :smile:

I just merge the bot PR in #7

**Comment by mwengren** [comment]
@ocefpaf yes I noticed the tests failed, but hadn't figured out where to get the checksum from just yet...  I guess I don't need to now!

**Comment by ocefpaf** [comment]
If you ever need to compute the checksum we have some [guidelines here](https://conda-forge.org/docs/meta.html#populating-the-hash-field), but we usually let the bot handle it and only interfere if things are not OK (which is pretty rare for pure python packages).

**Comment by mwengren** [comment]
Thanks, I found that as well just now.  So the bot checks all the CF source repos for new releases and generates the PR automatically?  Very handy.  I will try to remember that the next time and save the trouble :).

**Comment by ocefpaf** [comment]
> So the bot checks all the CF source repos for new releases and generates the PR automatically? Very handy.

Yep. We reached 5000 packages. There is no way we could keep growing without more automation.

**Comment by mwengren** [comment]
Yes, I noticed the list on the master repo gets truncated on GitHub, but that probably happened a long time ago...  Thanks!

**Pull request closed without merging**
